### ISSUE TITLE
Stability fees: incorrect documentation

### ISSUE THREAD

**Issue by Ana06** [makerdao/community#1050]
The following information is in the documentation (for example https://github.com/makerdao/community/blob/master/faqs/stability-fee.md):

> The Stability Fee is continuously compounding interest at a growth rate of x% per second. When the Stability Fee is set to 2%, for example, it will be accumulating at 1.0000000006279371924910298109948‬% per second, meaning that at the end of year one the user will owe exactly 2% on the principal. **Assuming the user put in 100 Dai, at the end of year one they would have 102.00, and at the end of year two, they would have 104.04.**

But the stability fee should reduce the amount of Dai a user has (or maybe this paragraph refers to the debt and not to the Dai someones has, but it doesn't seem like that because of the way in which is written). So I think it should be:

> Assuming the user put in 100 Dai, at the end of year one they would have 98.00, and at the end of year two, they would have 96,04.

If this is the case, I can send a PR to correct it. But if this is not the case, I would really appreciate an explanation of why the amount of Dai a user has increase with the stability fee.

**Comment by Davidutro** [comment]
Hi Ana!

Thanks for submitting this issue.

The best way to reword this, in my view, is this:

Old:
Assuming the user ~put in~ 100 Dai, at the end of year one they would have 102.00, and at the end of year two, they would have 104.04.

New:
Assuming the user **generated** 100 Dai, at the end of year one they would have 102.00, and at the end of year two, they would have 104.04.

The Stability Fee accrues in the "Dai-generated balance" of a given Vault that eventually needs to be repaid. Therefore, I believe it is accurate to have the number go up from 100, rather than down.

The amount of Dai a user has is not what is being talked about here, but rather it is the amount of Dai the user owes on his or her Vault.

**Comment by Ana06** [comment]
@Davidutro thank you for your answer and for the clear explanation. I think changing `put in` by `generated` is better than my proposal. :+1:

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
