### ISSUE TITLE
Sync ZenHub and Project Board

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#215]
We want updates on the ZenHub board to mirror the regular GitHub project board. I remember last week we talked about it as being a matter of configuration. Is that right? What do we need to do to make this happen?

**Comment by ghettodev** [comment]
I think the goal is to have parity in the zenhub version for advanced users but still allow the same basic view for people using the generic github view.

**Comment by amy-jung** [comment]
There is no simple syncing solution because Zenhub and Github Boards are used for the same purpose. Additionally, there is no automated feature for Zenhub. Therefore, Zenhub Workspace will be utilized for a big-picture view of project management (tasks mapped to internal process categories) and Github boards will show the status of issues. For clarification, the issues remain the same and automation still moves the issues accordingly.
