### ISSUE TITLE
Add section to Meetups Grants that talks about Community Development

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#217]
The meetups are the perfect place to get people involved with our various initiatives like translations, editing, grants, hackathons, governance, risk, etc. Let's encourage people hosting them to talk a little about the portal and the forum. 

- the Meetups Grants section should have instructions about how to contribute to Community Development 
- should this be one of the requirements for a grant?

**Comment by Davidutro** [comment]
I don't think it should be a grant requirement. We want as few obstacles as possible in the way of grantees otherwise it kills the amount of potential applications that might result in real meetups that produce value. 


Will think how to incorporate this. Perhaps in the landing page? Or somehow we can do an audit of all the sections and plug COMDEV whenever there is utility for the reader.

added this to the #242 Epic for Meetup Grants

**Comment by Davidutro** [comment]
closed because outdated
