### ISSUE TITLE
Poll folder truncated

### ISSUE THREAD

**Issue by 0xldr** [makerdao/community#2540]
https://github.com/makerdao/community/tree/master/governance/polls

The poll folder is being limited to 1_000 files. This is causing truncation of the folder and may lead to active poll files being impossible to access.

We need to speak to Jetstream to see if we are able to move some older polls to an archive folder or whether this will cause issues with the voting portal. If this is possible, we should agree on a protocol for archiving old polls, this could potentially be automated via GitHub Actions or similar.

Edit to add image:

![image](https://github.com/makerdao/community/assets/139177554/af7315ca-b73a-44c8-b0b1-299d90a483cc)

**Comment by 0xldr** [comment]
Having thought about this some more, moving polls to a new folder will break the link to the raw poll that is included as on chain data for the poll creation transaction, so this is unlikely to be a solution. Perhaps a better solution is transitioning to a new folder for new polls, e.g `governance/pollsv2` but this should still be discussed with the developers since it is possible that we are unable to do this.

**Comment by 0xldr** [comment]
We have asked Jetstream for their thoughts via their support channel on Discord.

**Comment by adamgoth** [comment]
After doing a little investigation, it doesn't look like this limitation is anything new. I've found threads as far back as 2016 discussing it. It's simply an artificial limitation that is only applied when viewing the files through the browser. The app itself still has programatic access to all the poll files. 

If you were having trouble finding a particular file, this article might help: https://briantjackett.com/2020/03/23/searching-for-truncated-files-in-github-folder/

Let us know if you have further questions or find information stating otherwise.

**Comment by adamgoth** [comment]
I can confirm that changing the folder structure would impact the frontend code. Can you explain more about the "end user" you are describing making these changes for? The governance portal itself was designed for the typical end user who wants to search through polls. The polling page contains search filters including search by text in the poll title. Then each poll detail page contains a link to the underlying github resource.

**Comment by adamgoth** [comment]
Unfortunately, it would require a decent amount of dev work. We can keep it in mind though if and when the time comes for an overhaul to how poll data is managed.

**Comment by 0xldr** [comment]
Thank you Adam, we are closing this issue for now
