### ISSUE TITLE
CDIP 3 MakerDAO Forum needs styling (previous: Improvement)

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#340]
**Description**
We’re looking for someone to put a pretty face on this forum and the portal.

Applicants will need to be able to deliver the client-side code.

The design should be minimally intrusive and adhere to general MakerDAO design principles and [styleguide](https://community-development.makerdao.com/contributing/visual-style-guide).

**Interested?**
If you feel you, or your team, is capable of handling this task: please feel free to ask questions in this thread, reach out to grants@makerdao.com, or DM in the chat @rich.brown.

Funding will be provided through the Grants Program framework.

Original Post: https://forum.makerdao.com/t/wanted-styling-for-this-forum-and-the-community-development-portal/150

**Comment by amy-jung** [comment]
Current working doc for forum styling by @scottrepreneur : https://www.figma.com/file/CGEGmtSi9TjCbcO6ylaND4/Maker-Forum?node-id=0%3A1 

✅Designs are approved
❗️Plug-ins need further review. Awaiting access from DevOps. Will have to wait a couple of weeks

**Comment by scottrepreneur** [comment]
[Revising based on feedback](https://docs.google.com/document/d/1kHeYc4MFuf5FAEzsp19p3QGfHj64YNvT8GxJ-GB407M/edit?ts=5dad8ef4#heading=h.uboqze5j6hvr)

**Comment by amy-jung** [comment]
Tasks

- [x] Research, dev setup & Match Colors
- [x] Pills for Remaining Buttons
- [x] Round Cards for menus
- [x] Rounded Cards for Posts List
- [ ] Category Cards for List
- [ ] Ensure category descriptions are completed
- [x] Cards on Individual Post?
- [ ] Custom links in menu: CDP Portal, Awesome MakerDAO, Community Portal
- [ ] Footer
- [x] Search updates
- [x] Customize post overview box

Dark Theme
- [ ] Switcher Component
- [ ] Alternative Logo

Landing Page
- [ ] Keep split between categories and latest posts?
- [ ] Persistent or dismissible banner with resources

Plug-ins
- [ ] Formatting toolbar - expands post/reply formatting options
- [ ] Trust Level on Avatars -  indicates admin assigned trust level on avatars
- [ ] Author Badges
- [ ] Category banners - add banners to enrich category post lists
- [ ] Mute Thread button - unsubscribe from threads that are noisy
- [ ] Change the Like icon - can be thumbs up instead

**Comment by twblack88** [comment]
Cdip: https://hackmd.io/eqNB8TzETCCyFDv_ZIvmcw?view
Project plan: https://hackmd.io/2SXYGSqMR3-tG5qA9EltHA?view

**Comment by scottrepreneur** [comment]
Seeking feedback: https://forum.makerdao.com/t/forum-theme-update-and-feedback/1144
Current implementation: https://github.com/scottrepreneur/makerdao-discourse-theme

**Comment by scottrepreneur** [comment]
[Release Candidate v1.0.0](https://github.com/scottrepreneur/makerdao-discourse-theme/releases/tag/v1.0.0)

**Comment by twblack88** [comment]
Implemented staging forum. 

- [ ] Decide what plugins are valuable, implement if valuable
- [ ] Get Foundation stakeholder sign off (design, risk, governance)
- [ ] Post sticky thread to forum telling everyone it's going to look different in two weeks, if you want to see in advance invite to staging forum. Intro any plugins we decide on too. 
- [ ] Launch current theme version to Forum

**Comment by twblack88** [comment]
Staging post to mirror on the Discourse instance: https://staging-forum.makerfoundation.com/t/new-maker-forum-theme-opt-in-and-available-now/51

As mentioned on our meeting 5-7, we've been lagging on the release of the update to the forum. This is particularly my fault as I said I would write this cross-post and kept leaving it off for shinier things. As a result, we've left deployment out and gotten less feedback from stakeholders, even though the theme are opt-in. This dynamic has lead to scope creep instead of completion though we did fire up the staging forum which is an invaluable addition. 

Lessons learned, since Scott implemented the forum design as requested/scoped. Moving forward the share that staging post that would be mirrored on live, and see if we can get stakeholders to voice any concerns before just offering the opt-in forum upgrade. 

Considering this is a good V1 of re-skinning and there is a good amount we could do in a v2, we should close this issue. Making a new CDIP wrapping outstanding tasks and current knowledge into a more robust forum design is 🔑 . At that point we could consider opt-in (current) or opt-out (proposed if the theme got fancy enough; via ember.js)

**Comment by twblack88** [comment]
revised list:
- [ ] Custom links in menu: CDP Portal, Awesome MakerDAO, Community Portal
- [ ] Footer
- [ ] Category Cards for List

Landing Page
- [ ] Keep split between categories and latest posts?
- [ ] Persistent or dismissible banner with resources

[Plug-ins](https://staging-forum.makerfoundation.com/t/the-great-plugin-debate/36/2)
- [ ] Formatting toolbar - expands post/reply formatting options
- [ ] Trust Level on Avatars -  indicates admin assigned trust level on avatars
- [ ] Author Badges
- [ ] Category banners - add banners to enrich category post lists
- [ ] Mute Thread button - unsubscribe from threads that are noisy
- [ ] Change the Like icon - can be thumbs up instead
