### ISSUE TITLE
Portal Content Sprint: Funding/Community projects

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#599]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

- [x] [Application Page](https://www.notion.so/Application-page-example-Development-grants-or-Join-the-translation-team-81eef02069bc47d2879d0c8bdc823d18) | Funding/Community projects | Writer: @amy-jung 
- [x] [Process Page](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821) | Funding/Community projects/Community projects process | Writer: @twblack88 

[Community Projects WIP Doc](https://hackmd.io/@rawhaus/HkYiKowa8/edit)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by amy-jung** [comment]
@twblack88 The Community Projects page is ready for review. https://hackmd.io/NOhEPX7dT7-W2eV4Cl0QAg

**Changed a few things:**
- Moved examples to bottom (to provide context after explaining process)
- Added intro to CDIP.
- Added a non-dev work example of a CDIP
- Rewrote some content to support when someone has an incomplete/not full created idea
- Added better transition into bounties
- Reframed "contribute to an existing community project" section
- Added Questions? section.

**What's not covered**
- Intro

**Other notes**
1. Where I'm struggling here is that "Community Projects" w/o context (having not seen or understanding "Funding") would have expectations that a list of our community projects. But really, this is about starting *New* Community Projects. Maybe we should consider changing the section name.
2. Make sure the Community Projects process page also has Community Development Initiative Proposal (CDIP) fully written out.

**Comment by amy-jung** [comment]
@twblack88 added issue #504 as a "dependency" as a reminder to update the info in there so we can close both ;)

**Comment by amy-jung** [comment]
@twblack88 

The doc needs to be worked on a bit more. 
- Needs to follow writing style guide (capitalized roles, capitalized titles, spell checker, removing of "you"s, tone, etc)
- Cross-check with the other Community Projects page to understand how they flow together/but can be stand-alone (any acronyms should be addressed at the beginning, etc). Needs further clarification - it's currently mixing between a generic process and CDIP

**Comment by twblack88** [comment]
Put in a bunch of work edits and the hack md links are now synced. you can see the commits on [this branch too](https://github.com/makerdao/community-portal/tree/tb-c-pages/content/en/funding/community-projects)

- [community projects landing page](https://hackmd.io/@rawhaus/HkYiKowa8/edit)
- [CDIPS process page](https://hackmd.io/LvpMRC3pS2OPYsrOL_I9VQ)

Work left that I can see (at this time, and to push at review):
- [ ] remove numbers from the process stepper. since the process stepper already produces numbers. 
- [ ] fix list bug since hover is doing weird things. 
- [ ] add images that aren't in the repo yet (have to get everyone aligned on images)
- [ ] make sure images are up to date
- [ ] collate notes for #504 and push that edit, review,  and PR

other notes 
1. I agree with your other note. I think it's best to rename the folder, header, filename etc. and find something that encompasses bounties, cdips, and points to grants. THat would probably wrap it all in a 🎁 
2. Ryan's design for the community projects included CDIPS on both pages. The landing page seemed like an intro and the second page was 95% of the content on CDIPS we had written. It seems to flow but it would be helpful to make sure it works. I think renaming might handle a bunch of the blocks since the CDIP process page is really about the image on there and the process post CDIP submission. Somewhat filler content but it's still helpful.

**Comment by twblack88** [comment]
ok cool it reads the pull requests accross repo's good job github. Fixed two tasks and got the drafts up for the communtiy pages. When we sync Amy, I'll have a build of the landing page that delineates the differences and also address the "initial research phase of a cdip" 💭
